менеджер работы с файлами
Boeing1337/RIT-WG-PROJECT pull request #16
Opened 2022-11-27 15:24 UTC by TRRIT

2022-11-29 16:04 UTC, Boeing1337 requested changes

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +    QuestionRepository questionRepository = new QuestionRepository();
private final

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +    KeywordsRepository keywordsRepository = new KeywordsRepository();
private final

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +    Scanner scanner = new Scanner(System.in);
private

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +    String aaaa = "Неверная команда.";
1) private final
2) имя переменной

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +    public Admin() {
Логика в конструкторе . Значит второй раз ее не вызвать не пересоздав класс - неправильно.

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +                    flag = false;
просто return и не надо будет менять флаг

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +    private StringBuilder menuWords() {
1) возвращаемое значение никто не использует
2) название метода - глагол

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +public class Admin {
Это не админ, это какой-то сервис.

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        return null;
null возвращать плохое решение

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        try {
try catch используется на ту часть где ожидается ошибка. Он должен замыкать как можно меньшую часть.

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +                        flag = false;
просто return и не надо менять флаг

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +    private void printQuestAnswer() {
Квест? =)

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        List<String> a = questionRepository.getQuestionByLetter(scanner.nextLine());
Что если я введу не букву а слово?

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        List<String> a = questionRepository.getQuestionByLetter(scanner.nextLine());
метод работает не правильно. Вместо того чтобы вернуть копию списка слов на букву он парсит контент, а он уже спаршен и сохранен в двух полях. Потом на 135 строке тут приходится скипать первый элемент по неочевидным причинам и идти по массиву чере 1.

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        int num = 1;
имя переменной не отображает её роль в коде

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        String quest = scanner.nextLine().trim();
имя переменной не отображает её роль в коде. quest != question

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +    private void addQuestAnswer() {
addAnswer()

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        List<String> que = questionRepository.getQuestionByLetter(word);
имя переменной не отображает её роль в коде

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        String word = scanner.nextLine();
имя переменной не отображает её роль в коде

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        int nume = 1;
имя переменной не отображает её роль в коде и почему она не в цикле

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        int number = Integer.parseInt(scanner.nextLine().trim()) - 1;
1) questionNumber
2) Если тут введут не число, то вся программа откатится в меню?

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        for (int i = 1; i < que.size(); i = i + 2) {
непонятный старт с 1 и прыжки через 1. Пришло что-то лишнее?

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        String q = scanner.nextLine();
имя переменной не отображает её роль в коде, пиdoor. Без негатива

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        String w = scanner.nextLine();
имя переменной не отображает её роль в коде

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        System.out.print("Какая первая буква ответа: ");
Вопрос можно задать проще. На какую букву. Игра может расширить правила и вообще бужет не понятно с чего такой вопрос возник.

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        List<String> qu = questionRepository.getQuestionByLetter(w);
имя переменной не отображает её роль в коде

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        int n = 1;
имя переменной не отображает её роль в коде

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        for (int i = 2; i < qu.size(); i = i + 2) {
непонятные прыжки через 2 и старт с 2

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        int numbe = Integer.parseInt(scanner.nextLine().trim()) - 1;
1) хуюмбе =)
2) Что будет если введут не число? Меню откатится в начало?

2022-11-29 16:04 UTC, Boeing1337 commented on src/main/java/dao/Admin.java
> +        String qw = scanner.nextLine();
3,14door, without negative

2022-11-29 16:05 UTC, loading199268 approved these changes

2022-11-29 16:09 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +    QuestionRepository questionRepository = new QuestionRepository();
исправил

2022-11-29 16:09 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +    KeywordsRepository keywordsRepository = new KeywordsRepository();
исправил

2022-11-29 16:09 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +    KeywordsRepository keywordsRepository = new KeywordsRepository();
исправил

2022-11-29 16:10 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +    Scanner scanner = new Scanner(System.in);
исправил

2022-11-29 16:10 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +    String aaaa = "Неверная команда.";
исправил

2022-11-29 16:25 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        List<String> qu = questionRepository.getQuestionByLetter(w);
исправил

2022-11-29 16:26 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +    public Admin() {
исправил

2022-11-29 16:27 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        int n = 1;
исправил

2022-11-29 16:43 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +    public Admin() {
исправил

2022-11-29 16:43 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        List<String> qu = questionRepository.getQuestionByLetter(w);
исправил

2022-11-29 16:43 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        int n = 1;
исправил

2022-12-01 09:49 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        for (int i = 2; i < qu.size(); i = i + 2) {
теперь метод называется правильно

2022-12-01 10:10 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        int numbe = Integer.parseInt(scanner.nextLine().trim()) - 1;
добавил проверку

2022-12-01 10:10 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        String qw = scanner.nextLine();
исправил все переменные

2022-12-01 13:40 UTC, loading199268 approved these changes, later dismissed

2022-12-01 14:57 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +                    flag = false;
исправил

2022-12-01 15:00 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +    private StringBuilder menuWords() {
исправил

2022-12-01 15:03 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +public class Admin {
исправил

2022-12-01 15:04 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        return null;
исправил

2022-12-01 15:05 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +                        flag = false;
исправил

2022-12-01 15:08 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +    private void printQuestAnswer() {
исправил

2022-12-01 15:09 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        List<String> a = questionRepository.getQuestionByLetter(scanner.nextLine());
использует первый чар

2022-12-01 15:11 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        List<String> a = questionRepository.getQuestionByLetter(scanner.nextLine());
так удобнее

2022-12-01 15:12 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        int num = 1;
исправил

2022-12-01 15:12 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        String quest = scanner.nextLine().trim();
исправил

2022-12-01 15:13 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +    private void addQuestAnswer() {
метод добавляет вопрос и ответ на вопрос, а не просто ответ

2022-12-01 15:14 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        List<String> que = questionRepository.getQuestionByLetter(word);
исправил

2022-12-01 15:14 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        String word = scanner.nextLine();
исправил

2022-12-01 15:14 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        int nume = 1;
исправил

2022-12-01 15:20 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        int number = Integer.parseInt(scanner.nextLine().trim()) - 1;
исправил

2022-12-01 15:20 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        for (int i = 1; i < que.size(); i = i + 2) {
0 индекс хранит в себе букву

2022-12-01 15:21 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        String q = scanner.nextLine();
исправил

2022-12-01 15:21 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        String w = scanner.nextLine();
исправил

2022-12-01 15:25 UTC, TRRIT commented on src/main/java/dao/Admin.java
> +        System.out.print("Какая первая буква ответа: ");
да

2022-12-01 16:12 UTC, Boeing1337 approved these changes

2022-12-01 16:12 UTC, merged