BUG
Boeing1337/RIT-WG-PROJECT pull request #35
Opened 2022-12-13 16:26 UTC by TRRIT

WG-44
Добавил хешированние парлей

2022-12-13 16:41 UTC, ArtiWell commented on src/main/java/tech/wg/servise/RegistrationUsers.java
> +            grammar.write("Вы успешно зарегистрировались в нашем детище!");
странное обращение к пользователю

2022-12-13 19:20 UTC, Boeing1337 requested changes

2022-12-13 19:20 UTC, Boeing1337 commented on src/test/java/tech/wg/servise/RegistrationUsersTest.java
> +//TODO проверить сценарий когда такой логин есть-
не сделано или забыл удалить?

2022-12-14 11:40 UTC, loading199268 commented on src/main/java/tech/wg/servise/Encryption.java
> +            throw new IllegalStateException("Нету нужного алгоритма", e);
Нет слова нету. Надо: "Нет нужного алгоритма"

2022-12-14 11:44 UTC, loading199268 submitted a review, later dismissed

2022-12-14 11:55 UTC, Boeing1337 approved these changes

2022-12-14 11:56 UTC, merged