feature: WG-46 dobavil GameMenu, sdelal 2 dop klassa dlyu sbora stati…
Boeing1337/RIT-WG-PROJECT pull request #36
Opened 2022-12-13 16:37 UTC by ArtiWell

добавил меню игры и сделал 2 дополнительных класса для гейм меню

2022-12-13 19:28 UTC, Boeing1337 requested changes

2022-12-13 19:28 UTC, Boeing1337 commented on src/main/java/tech/wg/servise/GameMenu.java
> +        while (inTheProcess) {
В бесконечных циклах переменная всегда называется по- разному, хотя несет тот же самый смысл. Нужно определиться с именем и использовать его.

2022-12-13 19:28 UTC, Boeing1337 commented on src/main/java/tech/wg/servise/GameMenu.java
> +    private void refund() {
Почему все сервисы сами работают с меню, а в двух с очками сделано по- другому?
Единообразние в преоритете.

2022-12-13 19:28 UTC, Boeing1337 commented on src/main/java/tech/wg/servise/GameMenu.java
> +                    inTheProcess = false;
нужно завершить программу полностью, иначе мы выйдем в меню логина или регистрации =)
System.stop(0) или как-то так

2022-12-13 19:28 UTC, Boeing1337 commented on src/main/java/tech/wg/servise/LadderScoreService.java
> +        List<ScoreEntity> topTen = scoreService.getTopPlayers(10);
Лучше вынести значение 10 в переменную и задавать ей значение из property файла. Тогда изменение выдаваемых игроков не потребует пересборки проекта

2022-12-14 09:19 UTC, ArtiWell commented on src/main/java/tech/wg/servise/GameMenu.java
> +        while (inTheProcess) {
отличная идея

2022-12-14 09:20 UTC, ArtiWell commented on src/main/java/tech/wg/servise/GameMenu.java
> +                    inTheProcess = false;
так нам и надо выйти в меню логина, но про систем стоп спасибо

2022-12-14 09:23 UTC, ArtiWell commented on src/main/java/tech/wg/servise/GameMenu.java
> +    private void refund() {
можно

2022-12-14 09:24 UTC, ArtiWell commented on src/main/java/tech/wg/servise/LadderScoreService.java
> +        List<ScoreEntity> topTen = scoreService.getTopPlayers(10);
изменение никогда не потребуется. метод надо было писать изначально без возможности выбора количества игроков

2022-12-14 11:57 UTC, loading199268 submitted a review, later dismissed

2022-12-14 12:17 UTC, Boeing1337 approved these changes

2022-12-14 12:17 UTC, merged